version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - dotnet restore

  build:
    commands:
      - echo "Building application..."
      - dotnet build

  post_build:
    commands:
      - echo "Publishing the app..."
      - dotnet publish -c Release -o output

artifacts:
  files:
    - '**/*'
